name: CI Pipeline

on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check code
      - uses: actions/checkout@v3

      - name: Build Installations
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Make program
        run: make

      - name: Tests
        run: make test
